### ISSUE TITLE
crawling deeper within channels

### ISSUE THREAD

**Issue by jongold** [jordanoverbye/gatsby-source-are.na#1]
Yo - this is so rad.

Hope I didn't miss anything - would be awesome to have a 'depth' config item or something to be able to fetch data from nested channels without specifying their slugs upfront in gatsby config.

say I have a meta channel that collects all of the stuff from my site:
```
meta
-> channel-a
-> channel-b
…
-> channel-z
```

it would be awesome to just specify `channelSlugs: ['meta'],` rather than `channelSlugs: ['meta
, 'channel-a', 'channel-b', …, 'channel-z']` etc.

lmk if you have thoughts about adding this and I can try to make it happen - won't touch it if that's outside of your interests for this project

**Comment by jordanoverbye** [comment]
Hey @jongold,

Thank you so much!

If I understand correctly, you can do that already - but you can only go 1 level down at the moment.

If you take a look at [this example](https://github.com/jordanoverbye/gatsby-source-are.na/tree/master/examples/portfolio) you can see that I've only specified one channelSlug in `gatsby-config`, but I'm able to query the contents of the 'inner' channels. 

So for that example, I just created a channel for each project, and then created a 'container' channel which has all of the project channels inside. That way you only have to specify one channel in the `gatsby-config`.

Does this solve your problem?

I think it would be awesome if you could query even deeper channels - I just didn't have time to do that. But if you wanted to and had time to do that, I would definitely merge in.

**Comment by jordanoverbye** [comment]
Hi @jongold , I'm going to close this issue. Please feel free to open a new one if you run into any issues.
