### ISSUE TITLE
help: config issue

### ISSUE THREAD

**Issue by mirshko** [jordanoverbye/gatsby-source-are.na#2]
hey there! 

thanks a bunch for making this source! i've been hunting for an easy to use cms thing that is simpler than a headless cms and are.na worked for my film photos.

so I went through and made an PAT and such, i used the personal access token for the config: 

<img width="1682" alt="Screenshot 2019-05-21 11 51 50 Redacted" src="https://user-images.githubusercontent.com/8116716/58086422-e6576280-7bbe-11e9-89f1-c1ff989d030b.png">

but im getting an error

<img width="472" alt="Screenshot 2019-05-21 11 53 39" src="https://user-images.githubusercontent.com/8116716/58086535-20c0ff80-7bbf-11e9-9cd5-29a44f27f745.png">

however, it does seem that the config is receiving the image nodes as it tries to download them, so i'm not sure what im doing wrong here. 

any help would be awesome. 

here is the repo
https://github.com/mirshko/dotdesign

**Comment by jordanoverbye** [comment]
Hello @mirshko ,

So sorry for the late reply! I don't know why I didn't see this earlier 

I've pulled down your repo and replicated your issue. I made a fix to this repo and published version `1.0.1`.  I then updated my local copy of your repo and it worked fine 👍

In the GraphQL editor I was able to run the following query successfully. Let me know how you go!

```
{
  arenaChannel(slug: {eq: "2018-03-12t1622"}) {
    title
    children {
      __typename
      ... on ArenaBlock {
        title
        image {
          childImageSharp {
            fluid(maxWidth: 1280) {
              base64
            }
          }
        }
      }
    }
  }
}
```
